Port mkdocs and mkdocs-material to zensical
There are some concerns regarding mkdocs-material ownership and at the
moment we see discrepancies between pypi and the github repositories,
for instance mkdocs-get-deps dooesn't have the last 2 tags published in
github.

Additionally, we see that mkdocs doesn't seem to have a clear license, and we also
see that mkdocs 2.0 is incompatible with mkdocs-material, so at this
point we need to consider something else.

The main 3 options that we see are:
1- Upgrade to mkdocs 2.0 - without material and apparently without
plugins
2- Replace mkdocs and material for zensical
3- Replace mkdocs and material for properdocs

In the community zensical seems to be the one with most traction and
also has the advantage of having significantly less dependencies.

This is incomplete at the moment until we decide that indeed we want to
use zensical, pending tasks are:

1- Fix docs/stylesheets/extra.css
2- Port mkdocs.yaml to zensical.toml
3- Check all the markdown extensions, can we remove some?

Signed-off-by: Juan-Luis de Sousa-Valadas Castaño <juanluisvaladas@users.noreply.github.com>

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -16,15 +16,15 @@ endif
 DOCKER ?= docker
 TARGET_VERSION ?= latest
 # mkdocs.yml refuses to live in the docs-directory, this is why "cd .." is needed
-# gives: "Error: The 'docs_dir' should not be the parent directory of the config file."
+# gives: "Er The 'docs_dir' should not be the parent directory of the config file."
 # even if docs_dir is "."
-docs: .require-mkdocs cli
-	cd .. && PYTHONPATH=$(CURDIR)/mkdocs_modules K0S_VERSION=$$('$(k0s_binary_path)/$(k0s_binary)' version) mkdocs build --strict
+docs: .require-zensical cli
+	cd .. && PYTHONPATH=$(CURDIR)/zensical_modules K0S_VERSION=$$('$(k0s_binary_path)/$(k0s_binary)' version) zensical build --strict
 
-.PHONY: .require-mkdocs
-.require-mkdocs:
-	@which mkdocs >/dev/null 2>/dev/null || { \
-	  echo 'mkdocs required, use pip install --disable-pip-version-check -r $(CURDIR)/requirements.txt' >&2; \
+.PHONY: .require-zensical
+.require-zensical:
+	@which zensical >/dev/null 2>/dev/null || { \
+	  echo 'zensical required, use pip install --disable-pip-version-check -r $(CURDIR)/requirements.txt' >&2; \
 	  exit 1; \
 	}
 
